name: landsafe_edge_mobile
description: "LANDSAFE NER — Offline-First Edge AI Citizen Reporting & Early Warning App (SIH 2026)"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.3+1
  path: ^1.9.0
  onnxruntime: ^1.4.1
  camera: ^0.10.5+9
  geolocator: ^11.0.0
  connectivity_plus: ^6.0.3
  http: ^1.2.1
  flutter_local_notifications: ^17.1.2
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/models/edge_severity_model.onnx
